databases:
  - name:mort 
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    plan: free
    name: mort 
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 -m
    region: frankfurt
    envVars:
      - key: APP_ID
        value: "25978936"
      - key: API_HASH
        value: "cf754dc655df0e7deff36732dbfff074"
      - key: STRING_SESSION
        sync: false
        value: Asia/Amman
      - key: PYTHON_VERSION
        value: "3.11.7"
      - key: DATABASE_URL
        fromDatabase:
          name:mort 
          property: connectionString
    autoDeploy: false