databases:
  - name: On
    ipAllowList: []
    region: frankfurt
    plan: free

services:
  - type: web
    plan: free
    name: On
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 main.py
    region: frankfurt
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: ENV
        value: ANYTHING
      - key: TZ
        value: Asia/Amman
      - key: PYTHON_VERSION
        value: "3.10.9"
      - key: DATABASE_URL
        fromDatabase:
          name: On
          property: connectionString
    autoDeploy: false
