databases:
  - name: mort
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    plan: free
    name: mort
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 mor.py
    region: frankfurt
    envVars:
      - key: APP_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: ENV
        value: ANYTHING
      - key: STRING_SESSION
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.7"
      - key: DATABASE_URL
        fromDatabase:
          name: mort
          property: connectionString
    autoDeploy: false
